[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">= 3.0"
name = "hypickle"
version = "1.0.17"
dependencies = [
  "requests",
  "rich",
  "deepdiff",
  "mplcursors",
]
readme = "README.md"
license = {file = "LICENSE"}

[project.scripts]
hypickle = "main"

[tool.setuptools]
py-modules = []